Repository DragonBox/u3d, pull requests merged in 2018-04, with the labels that each got.

#272 u3d/prettify: Catch Enlighten jobs failure
  config/log_rules.json
Labels: bug

#273 u3d/prettify: fix exception rule start pattern
  config/log_rules.json
Labels: enhancement

#279 u3d/prettify: catch build pipeline messages
  config/log_rules.json
Labels: enhancement

#280 u3d/list: display full revision number (prepares for #274)
  lib/u3d/commands.rb
  lib/u3d/installation.rb
  spec/support/installations.rb
Labels: enhancement

#281 Preparing release for 1.0.20
  CHANGELOG.md
Labels: nochangelog

#283 u3d/console: an interactive version of u3d (Fixes #265)
  README.md
  docs/assets/u3d_console.png
  lib/u3d/commands.rb
  lib/u3d/commands_generator.rb
Labels: enhancement

#297 u3d/* automatically retry admin privilege elevation #236
  lib/u3d_core/command_executor.rb
  spec/u3d_core/command_executor_spec.rb
Labels: enhancement

#304 u3d/install do not ask for root password
  lib/u3d_core/command_executor.rb
  spec/u3d_core/command_executor_spec.rb
Labels: enhancement
